### ISSUE TITLE
[GK Grid] Nie dziala w Safari

### ISSUE THREAD

**Issue by teitbite** [GavickPro/GK-Grid#8]
W safari nie wyliczane jest polozenie blokow, przec co wszystkie sa wyswietlane na sobie:

https://meganoticias.mx/portada-4

<img width="1300" alt="zrzut ekranu 2015-09-19 o 10 32 59" src="https://cloud.githubusercontent.com/assets/1392802/9975352/e049c7d2-5eb9-11e5-8061-e75573a54a29.png">

Updatowalem modul u klienta, probowalem kilku innych ustawien ale nic nie dziala.

https://meganoticias.mx/administrator?meganoti
User: teitbite
Pass: kj997

https://www.gavick.com/forums/news-joomla30/grid-on-safari-47932?p=241034#p241034

**Comment by dziudek** [comment]
Bardzo dziwny case - wygląda to tak jakby klient miał jakiś błąd parsowania inline CSS-a generowanego przez różne moduły.

Jedyne co mogę zasugerować: niech włączy override.css i wrzuci tam:

```css

#gk-grid-755 .gkGridElement { border: none; }
.gkGridGK5 .gkImgDesktop { display: block; } .gkGridGK5 .gkImgTablet, .gkGridGK5 .gkImgMobile { display: none; } 
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-1-1 { height: 40%; width: 66.6666666667%; left: 0%; top: 0%; z-index: 1; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-2-1 { height: 20%; width: 33.3333333333%; left: 66.6666666667%; top: 0%; z-index: 2; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-3-1 { height: 20%; width: 33.3333333333%; left: 66.6666666667%; top: 20%; z-index: 3; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-4-1 { height: 20%; width: 50%; left: 0%; top: 40%; z-index: 4; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-5-1 { height: 40%; width: 16.6666666667%; left: 50%; top: 40%; z-index: 5; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-6-1 { height: 40%; width: 16.6666666667%; left: 66.6666666667%; top: 40%; z-index: 6; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-7-1 { height: 40%; width: 16.6666666667%; left: 83.3333333333%; top: 40%; z-index: 7; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-8-1 { height: 20%; width: 50%; left: 0%; top: 60%; z-index: 8; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-9-1 { height: 20%; width: 33.3333333333%; left: 0%; top: 80%; z-index: 9; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-10-1 { height: 20%; width: 33.3333333333%; left: 33.3333333333%; top: 80%; z-index: 10; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-11-1 { height: 20%; width: 33.3333333333%; left: 66.6666666667%; top: 80%; z-index: 11; }
@media (max-width: 840px) { 
.gkGridGK5 .gkImgTablet { display: block; } .gkGridGK5 .gkImgDesktop, .gkGridGK5 .gkImgMobile { display: none; } 
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-1-1 { height: 50%; width: 75%; left: 0%; top: 0%; z-index: 1; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-2-1 { height: 25%; width: 25%; left: 75%; top: 0%; z-index: 2; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-3-1 { height: 25%; width: 25%; left: 75%; top: 25%; z-index: 3; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-4-1 { height: 25%; width: 25%; left: 0%; top: 50%; z-index: 4; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-5-1 { height: 25%; width: 25%; left: 25%; top: 50%; z-index: 5; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-6-1 { height: 25%; width: 25%; left: 50%; top: 50%; z-index: 6; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-7-1 { height: 25%; width: 25%; left: 75%; top: 50%; z-index: 7; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-8-1 { height: 25%; width: 25%; left: 0%; top: 75%; z-index: 8; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-9-1 { height: 25%; width: 25%; left: 25%; top: 75%; z-index: 9; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-10-1 { height: 25%; width: 25%; left: 50%; top: 75%; z-index: 10; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-11-1 { height: 25%; width: 25%; left: 75%; top: 75%; z-index: 11; }
} 
@media (max-width: 600px) { 
.gkGridGK5 .gkImgMobile { display: block; } .gkGridGK5 .gkImgDesktop, .gkGridGK5 .gkImgTablet { display: none; } 
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-1-1 { height: 16.6666666667%; width: 100%; left: 0%; top: 0%; z-index: 1; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-2-1 { height: 16.6666666667%; width: 50%; left: 0%; top: 16.6666666667%; z-index: 2; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-3-1 { height: 16.6666666667%; width: 50%; left: 50%; top: 16.6666666667%; z-index: 3; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-4-1 { height: 16.6666666667%; width: 50%; left: 0%; top: 33.3333333333%; z-index: 4; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-5-1 { height: 16.6666666667%; width: 50%; left: 50%; top: 33.3333333333%; z-index: 5; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-6-1 { height: 16.6666666667%; width: 50%; left: 0%; top: 50%; z-index: 6; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-7-1 { height: 16.6666666667%; width: 50%; left: 50%; top: 50%; z-index: 7; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-8-1 { height: 16.6666666667%; width: 50%; left: 0%; top: 66.6666666667%; z-index: 8; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-9-1 { height: 16.6666666667%; width: 50%; left: 50%; top: 66.6666666667%; z-index: 9; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-10-1 { height: 16.6666666667%; width: 50%; left: 0%; top: 83.3333333333%; z-index: 10; }
#gk-grid-755 .gkGridElement.gkGrid-mn-grid-11-1 { height: 16.6666666667%; width: 50%; left: 50%; top: 83.3333333333%; z-index: 11; }
}
```

Gdyby zmieniał coś w ustawieniach modułu to niech skopiuje sobie nowy kod CSS raz jeszcze do override.css
